############################
# 公网服务器开启端口: 6080 #
############################

# 官网 https://gofrp.org/zh-cn/docs/overview/

# 公网服务器ip
serverAddr = "88.218.238.208"
# 服务端frps与客户端frpc绑定进行通信的端口(此端口只作为两者通信用，具体应用还需要开启相应的端口)
serverPort = 7000

[[proxies]]
name = "site001"
type = "tcp"
localIP = "127.0.0.1"
localPort = 80
## 原理 http://88.218.238.208:6080 --->>> 127.0.0.1:80
remotePort = 6080
loadBalancer.group = "web"
#loadBalancer.groupKey = "str123"
